"use client"

import './globals.css'
import { Inter } from 'next/font/google'

import { Header as Heade } from '../components/layout/Header/component'
const inter = Inter({ subsets: ['latin'] })
import Head from 'next/head'
import { AuthProvider } from '@/context/AuthContext'
import { ModalProvider } from '@/context/modalContext'
import { MusicProvider } from '@/context/MusicContext'
import { Aside } from '@/components/layout/aside/component'


export const metadata = {
  title: 'Music',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <MusicProvider>
        <AuthProvider>
          <ModalProvider>
            <Head>
              <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
                rel="stylesheet" />
            </Head>
            <body className={inter.className}>
                {children}
            </body>
          </ModalProvider>
        </AuthProvider>
      </MusicProvider>
    </html>
  )
}
